


### ONLY DOCTOR CAN CREATE A COMMENT ###
### IF A USER IS A DOCTOR AND THE USER IS ASSOCIATED WITH THE PATIENT ###
    ### THEN THE USER CAN: ###
        ### 1. GET THE Q&A OF THE PATIENT ###
        ### 2. CREATE A COMMENT FOR THE QUESTION ###