"""Updated modded models

Revision ID: 4248dee56464
Revises: 84cd13627dcf
Create Date: 2023-06-08 14:23:37.733563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4248dee56464'
down_revision = '84cd13627dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
